[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_LOG_LEVEL=3
lib_deps = 
    bluedroid
